tf/core/iam_nocadmin.tf

@sorah 
Trust policyをtypoして作ってしまった

noadmin: Allow iam:UpdateAssumeRolePolicy

---

tf/core/iam_nocadmin.tf

nocadmin: Allow s3:* on rk-syslog bucket

---

tf/core/iam_nocadmin.tf

nocadmin: Allow iam:PutRolePermissionsBoundary

---

tf/core/bastion.tf
tf/core/vpc.tf
tf/k8s/aws.tf

https://github.com/ruby-no-kai/rubykaigi-nw/issues/30
- deploy per-AZ NAT gateway for private subnets :new:
- deploy NAT gateways for onpremises subnets

NAT gateways revive for rk23

---

tf/himari/config.ru

himari: register oidc client for ops-lb

---

tf/himari/config.ru

himari: allow everyone to access ops-lb services

---

tf/grafana/grafana.jsonnet
tf/grafana/grafana.tf
tf/grafana/iam.tf

grafana: CloudWatch datasource

---

gen/k8s/dhcp/deployment.yml
gen/k8s/dns-cache/deployment.yml
gen/k8s/radius/deployment.yml
gen/k8s/syslog/deployment.yml
k8s/dhcp/deployment.jsonnet
k8s/dns-cache/deployment.jsonnet
k8s/radius/deployment.jsonnet
k8s/syslog/deployment.jsonnet
tf/grafana/grafana.jsonnet
tf/k8s-cert-manager/cert-manager.jsonnet
tf/prom/blackbox-exporter.jsonnet
tf/prom/cloudwatch-exporter.jsonnet
tf/prom/kube-prometheus-stack.jsonnet
tf/prom/snmp-exporter.jsonnet

k8s: resource requests

---

tf/grafana/aws.tf
tf/grafana/grafana.jsonnet
tf/grafana/grafana.tf
tf/grafana/iam.tf
tf/grafana/oidc_client.tf
tf/jsonnet.rb

Grafana pubic dashboard

---

gen/k8s/syslog/daemonset.yml
k8s/syslog/daemonset.jsonnet

k8s: add resources requests for fluent-bit daemonset

---

tf/admin-iam/noc_admin.tf

Allow TakeoutUser role to NocAdminBase

---

tf/himari/config.ru

tf/himari: ops-lb OIDC client

---

tf/prom/gen/snmp.yml
tf/prom/snmp-exporter.config/config.jsonnet
tf/prom/snmp-exporter.config/if_mib.libsonnet
tf/prom/snmp-exporter.config/juniper_alarm.libsonnet
tf/prom/snmp-exporter.config/juniper_bgp.libsonnet
tf/prom/snmp-exporter.config/juniper_chassis.libsonnet
tf/prom/snmp-exporter.config/juniper_jdhcp.libsonnet
tf/prom/snmp-exporter.config/juniper_virtualchasiss.libsonnet

- Contributes to https://github.com/ruby-no-kai/rubykaigi-net/issues/99

more Juniper MIBs

---

tf/himari/config.ru

tf/himari: grafana 2024

---

tf/admin-iam/noc_admin.tf

Allow apprunner actions to NocAdmin role

---

tf/admin-iam/noc_admin.tf
tf/attendee-gate/.mairu.json
tf/attendee-gate/.terraform.lock.hcl
tf/attendee-gate/README.md
tf/attendee-gate/aws.tf
tf/attendee-gate/backend.tf
tf/attendee-gate/ecr.tf
tf/attendee-gate/iam_events.tf
tf/attendee-gate/iam_lambda.tf
tf/attendee-gate/iam_states.tf
tf/attendee-gate/lambda.tf
tf/attendee-gate/locals.tf
tf/attendee-gate/s3.tf
tf/attendee-gate/scheduler.tf
tf/attendee-gate/ssm.tf
tf/attendee-gate/states.tf
tf/attendee-gate/versions.tf
tf/core/iam_gha_docker-push.tf

https://rubykaigi.slack.com/archives/C08FEJUSMT7/p1741265387844749

add attendee-gate

---

itamae/roles/plat/templates/etc/nftables/plat.conf

plat: reset expired TCP connection

---

itamae/cookbooks/bird/default.rb
itamae/roles/plat/default.rb
itamae/roles/plat/templates/etc/bird/bird.conf.d/plat.conf

Closes https://github.com/ruby-no-kai/rubykaigi-net/issues/174

plat: pref64n routes to require default route

---

gen/k8s/prom/nat-6x.yml
itamae/cookbooks/bird/default.rb
itamae/cookbooks/bird/templates/etc/bird/bird.conf
itamae/roles/plat/templates/etc/nftables/plat.conf
k8s/prom/nat-6x.jsonnet

plat: prometheus-bird-exporter

---

itamae/roles/plat/templates/etc/bird/bird.conf.d/plat.conf
itamae/roles/plat/templates/etc/systemd/network/00-tun-siit.network

plat: Blackhole traffic that do not match tun-siit routing table

---

gen/k8s/prom/cloudprober.yml
gen/k8s/prom/nat-6x.yml
gen/k8s/prom/snmp.yml
k8s/prom/cloudprober.jsonnet
k8s/prom/nat-6x.jsonnet
k8s/prom/relabel_instance_short.libsonnet
k8s/prom/snmp.jsonnet

instance=xxx.yyy.rubykaigi.net
instance_short=xxx.yyy
for simplifying visualisation purpose

prom: add instance_short label

---

itamae/helpers.rb
itamae/hosts/nat-61.venue.rubykaigi.net/default.rb
itamae/hosts/nat-62.venue.rubykaigi.net/default.rb
itamae/hosts/nat-69.tkyk.rubykaigi.net/default.rb
itamae/roles/plat/templates/etc/bird/bird.conf.d/plat.conf
itamae/roles/plat/templates/etc/nftables/plat.conf
itamae/site.rb

plat: Accept prefixes for NAT outer addresses

---

tf/admin-iam/kaigi_staff.tf
tf/admin-iam/noc_admin.tf
tf/admin-iam/streaming_staff.tf

https://aws.amazon.com/about-aws/whats-new/2025/08/aws-management-console-assigning-color-aws-account/

AWSManagementConsoleBasicUserAccess
